# Generated by Django 5.1.6 on 2025-10-31 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='created_at',
            new_name='date',
        ),
    ]
