# Generated by Django 5.1.6 on 2025-11-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_announcement_rename_name_doctor_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blockchain_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
