# Generated by Django 5.1.6 on 2025-11-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_patienthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='tx_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
