# Generated by Django 5.1.6 on 2025-11-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_patient_tx_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_password_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_password_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
