# Generated by Django 5.1.6 on 2025-11-13 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_consultationrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultationRecord',
        ),
    ]
