# Generated by Django 5.1.6 on 2025-11-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_patientvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
