# Generated by Django 5.1.6 on 2025-11-19 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_patientvisit_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='sent_to_patient',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PatientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.patientvisit')),
            ],
        ),
    ]
